import fs from 'node:fs';
const path = 'agents/console/app.js';
let s = fs.readFileSync(path, 'utf8');
const oldText = `    const previous = finite(event?.previousValue);\n    const current = finite(event?.currentValue);\n    if (previous !== null && current !== null) {\n      const absDelta = Math.abs(current - previous);\n      const base = Math.max(Math.abs(previous), 1e-9);\n      const rel = absDelta / base;\n      score += Math.min(25, rel * 20);\n      if (absDelta > 1) score += Math.min(10, Math.log10(absDelta + 1) * 3);\n    }`;
const newText = `    const previous = finite(event?.previousValue);\n    const current = finite(event?.currentValue);\n    if (previous !== null && current !== null) {\n      const absDelta = Math.abs(current - previous);\n      const base = Math.max(Math.abs(previous), 1e-9);\n      const unit = String(event?.unit || '').toUpperCase();\n      if (unit === 'USD') {\n        score += Math.min(30, Math.log10(absDelta + 1) * 10);\n        if (base >= 10 && absDelta >= 1) score += Math.min(5, (absDelta / base) * 5);\n      } else {\n        score += Math.min(10, (absDelta / base) * 5);\n      }\n    }`;
if (!s.includes(oldText)) throw new Error('expected salience numeric block missing');
if (s.includes(newText)) throw new Error('salience magnitude repair already present unexpectedly');
s = s.replace(oldText, newText);
fs.writeFileSync(path, s, 'utf8');
console.log('economic-magnitude salience repair applied');
