import fs from 'node:fs';
const path='agents/console/app.js';
let s=fs.readFileSync(path,'utf8');
const old=`    if (includesAny(q, ['concentration risk', 'concentration most visible', 'риск концентрации', 'концентрация риска'])) return unknown(\n      ru\n        ? 'В текущем Ask нет нормализованного cross-company exposure matrix по активам, протоколам и сетям. Поэтому я не могу честно назвать компанию с максимальной concentration risk. APR или одна позиция не являются заменой exposure concentration.'\n        : 'The current Ask has no normalized cross-company exposure matrix across assets, protocols and chains, so I cannot honestly name the highest concentration risk. APR or one visible position is not a substitute for exposure concentration.',\n      'Console capability map'\n    );`;
const neu=`    if (includesAny(q, ['concentration risk', 'concentration most visible', 'риск концентрации', 'концентрация риска'])) return productiveConcentrationAnswer(lang);`;
const n=s.split(old).length-1;
if(n!==1) throw new Error('expected exactly one superseded concentration boundary, found '+n);
s=s.replace(old,neu);
fs.writeFileSync(path,s);
console.log('superseded concentration UNKNOWN boundary replaced');
